### ISSUE TITLE
Fine registration with single camera gives silly error

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc#104]
DavidC got the following error when doing fine calibration with only a single camera:

```
Fine calibration: capturing human-sized object
Before: overall correspondence error 0.0. Per-camera correspondence, ordered worst-first:
        camnum=1, correspondence=0.0, weight=0.0
Step 1: camera 1, correspondence error 0.0, overall correspondence error 0.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\cwipc_register.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\cwipc\scripts\cwipc_register.py", line 74, in main
    reg.run()
  File "C:\Program Files\Python311\Lib\site-packages\cwipc\scripts\cwipc_register.py", line 362, in run
    new_pc = self.fine_calibration(pc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\cwipc\scripts\cwipc_register.py", line 557, in fine_calibration
    ok = aligner.run()
         ^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\cwipc\registration\multicamera.py", line 118, in run
    self.aligner.run(camnum_to_fix)
  File "C:\Program Files\Python311\Lib\site-packages\cwipc\registration\fine.py", line 70, in run
    assert len(self.per_camera_pointclouds) > 1
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by jackjansen** [comment]
Fixed in 7.5.3
