### ISSUE TITLE
Synthetic Point Cloud is Disappearing in 1-2 seconds

### ISSUE THREAD

**Issue by ashutosh3308** [cwi-dis/cwipc#138]
Working on a `Windows 11` computer (Ashu Laptop), I installed the nightly build version (`7.5.3+c1e92e8`) of `cwipc`, and everything was installed correctly. Before installing this, the old version was deleted. When I run the command `cwipc_view --synthetic`,  the `synthetic` point cloud gets displayed for 1-2 seconds and then it disappears and I get the following error 

`Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\cwipc\scripts\cwipc_view.py", line 54, in main
    visualizer.run()
  File "C:\Program Files\Python39\lib\site-packages\cwipc\io\visualizer.py", line 111, in run
    ok = self.draw_pc(pc)
  File "C:\Program Files\Python39\lib\site-packages\cwipc\io\visualizer.py", line 182, in draw_pc
    return self.interact_visualiser() # Note we pass the original pc to interact, not the modified pc.
  File "C:\Program Files\Python39\lib\site-packages\cwipc\io\visualizer.py", line 188, in interact_visualiser
    cmd = self.visualiser.interact(None, "?h\x1bq .<+-cwamirsn0123456789", interaction_duration)
  File "C:\Program Files\Python39\lib\site-packages\cwipc\util.py", line 794, in interact
    rv = cwipc_util_dll_load().cwipc_sink_interact(self.as_cwipc_sink_p(), cprompt, cresponses, millis)
OSError: exception: access violation reading 0x0000000000000000
grab: capture_duration: count=3, average=0.007, min=0.006, max=0.008
grab: capture_pointcount: count=3, average=160000.000, min=160000, max=160000
grab: capture_latency: count=3, average=0.007, min=0.007, max=0.007`

**Comment by ashutosh3308** [comment]
I am working with only one `Intel realsense` `D455` camera when I run this command to do the `registration` `cwipc_register --noregister`. I get the following error:

`Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\cwipc_register.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Program Files\Python39\lib\site-packages\cwipc\scripts\cwipc_register.py", line 78, in main
    reg.run()
  File "C:\Program Files\Python39\lib\site-packages\cwipc\scripts\cwipc_register.py", line 275, in run
    self.capturerFactory, self.capturerName = cwipc_genericsource_factory(self.args)
  File "C:\Program Files\Python39\lib\site-packages\cwipc\scripts\_scriptsupport.py", line 174, in cwipc_genericsource_factory
    kinect.cwipc_kinect_dll_load()
  File "C:\Program Files\Python39\lib\site-packages\_cwipc_kinect\__init__.py", line 57, in cwipc_kinect_dll_load
    _cwipc_kinect_dll_reference = ctypes.CDLL(libname)
  File "C:\Program Files\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed`

**Comment by jackjansen** [comment]
@ashutosh3308 , these are two completely different errors....

For the second problem (the DLL initialisation failed error): this looks like the VCRedist problem (#124). The top-level readme has a fix for this: you have to ensure that the Microsoft C++ Redist that is installed on your computer is the most recent version (it's in the section on Windows troubleshooting).

**Comment by jackjansen** [comment]
The first issue (the one from the title) I am also seeing, but I have never managed to catch it. Mainly because I have never found a way to repeat it when I want it, and it seems you have such a way.

Could you please run under the debugger (it may be better to use the command `python -m cwipc.scripts.cwipc_view --synthetic` in stead of the shorter `cwipc_view --synthetic`). I mean: the Visual Studio debugger.

When the access violation on the NULL pointer happens I would like to get a stack trace.

**Comment by jackjansen** [comment]
@ashutosh3308 can you please check whether this issue still exists, and either

- close it if its gone, or
- provide details and re-assign to me.
