### ISSUE TITLE
Can't run cwipc_calibrate and cwipc_kinectcalibrate

### ISSUE THREAD

**Issue by AR-Vsx** [cwi-dis/cwipc#5]
When I try to run `cwipc_callibrate.exe --kinect` I get the following error 

Traceback (most recent call last):
  File "C:\cwipc\build\venv\Scripts\cwipc_calibrate-script.py", line 33, in <module>
    sys.exit(load_entry_point('cwipc-util==7.1', 'console_scripts', 'cwipc_calibrate')())
  File "C:\cwipc\build\venv\lib\site-packages\cwipc_util-7.1-py3.9.egg\cwipc\scripts\cwipc_calibrate\__main__.py", line 69, in main
    ok = prog.open(grabber, clean=args.clean, reuse=(args.reuse or args.auto))
  File "C:\cwipc\build\venv\lib\site-packages\cwipc_util-7.1-py3.9.egg\cwipc\scripts\cwipc_calibrate\calibrator.py", line 65, in open
    ok = self.grabber.open()
  File "C:\cwipc\build\venv\lib\site-packages\cwipc_util-7.1-py3.9.egg\cwipc\scripts\cwipc_calibrate\livegrabber.py", line 30, in open
    self.grabber = self.captureCreator()
  File "C:\cwipc\build\venv\lib\site-packages\cwipc_kinect-7.1-py3.9.egg\_cwipc_kinect\__init__.py", line 66, in cwipc_kinect
  File "C:\cwipc\build\venv\lib\site-packages\cwipc_kinect-7.1-py3.9.egg\_cwipc_kinect\__init__.py", line 46, in _cwipc_kinect_dll
RuntimeError: Dynamic library cwipc_kinect not found

 When trying to run `cwipc_kinectcalibrate` I also get an error

Traceback (most recent call last):
  File "C:\cwipc\build\venv\Scripts\cwipc_kinectcalibrate-script.py", line 33, in <module>
    sys.exit(load_entry_point('cwipc-kinect==7.1', 'console_scripts', 'cwipc_kinectcalibrate')())
  File "C:\cwipc\build\venv\Scripts\cwipc_kinectcalibrate-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\python 3.9.0\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\python 3.9.0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_cwipc_kinect.scripts.cwipc_kinectcalibrate'

**Comment by jackjansen** [comment]
`cwipc_kinectcalibrate` is a thing left over from the distant past, it doesn't't exist anymore. I will remove the reference.

`cwipc_calibrate --kinect` is indeed what you should use. But: you have to have your system environment variable `PATH` set correctly. Go to `System Properties` -> `Environment Variables` -> `System Variables` -> `Path` and ensure it contains

- `C:\Program Files\Azure Kinect SDK v1.4.1\sdk\windows-desktop\amd64\release\bin`
- `C:\Program Files\Azure Kinect Body Tracking SDK\tools`

And that you have _not_ copied the Kinect DLLs into your build directory (as you said that you have done in your other bug report). There is some magic dependency of the Kinect DLLs, I think on some Cuda or Nvidia DLLs or something.

**Comment by AR-Vsx** [comment]
Thank you, I figured that it might have not been the greatest idea to copy dll files. I added the Paths you suggested but I still had to add `\cwipc\build\bin\RelWithDebInfo` to `PATH` in order to run `cwipc_calibrate --kinect`

**Comment by jackjansen** [comment]
Hmm. Everything should have been installed to `installed/bin`... You _did_ put that directory on your PATH?

If the instructions on this weren't clear then let me know.

**Comment by AR-Vsx** [comment]
When I add `installed/bin` to PATH I get this error: 

FileNotFoundError: Could not find module 'C:\cwipc\installed\bin\cwipc_kinect.dll' (or one of its dependencies). Try using the full path with constructor syntax.

But when I add `build\bin\RelWithDebInfo`  to PATH it works

**Comment by jackjansen** [comment]
There is a new release v7.2, https://github.com/cwi-dis/cwipc/releases/tag/v7.2

It is probably best to uninstall all remains of previous attempts before installing this.

I'm reasonably sure it should address the issues here. Please reopen this issue (with details) if that is not the case.
